### ISSUE TITLE
ModuleNotFoundError: No module named 'wget'

### ISSUE THREAD

**Issue by CangHaiQingYue** [harsimrat-eyeem/holy-edge#4]
I didn‘t find any module named ’wget‘.
I think its used to download HEDdate?
where can I downfind the moduel?

**Comment by harsimrat-eyeem** [comment]
Hi. `wget` is linux command line usually comes preinstalled with most *nix distributions. Are you on Windows by any chance ?

**Comment by CangHaiQingYue** [comment]
Thanks！ I'm on Linux(ubuntu16.04).  And I just installed wget. I'll try this model soon.
