### ISSUE TITLE
pretrained model invalid

### ISSUE THREAD

**Issue by loveltyoic** [harsimrat-eyeem/holy-edge#5]
Hi, when I run `git lfs fetch && git lfs pull`,
it outputs
```
Git LFS: (0 of 2 files) 0 B / 585.83 MB
batch response: This repository is over its data quota. Purchase more data packs to restore access.
```
Could you upload the model elsewhere?

**Comment by harsimrat-eyeem** [comment]
Hi there, 

Pre-trained VGG [model](https://mega.nz/?lipi=urn%3Ali%3Apage%3Ad_flagship3_messaging%3BeXVpUjFUQ7OJbv5mIHkhIA%3D%3D#!YU1FWJrA!O1ywiCS2IiOlUCtCpI6HTJOMrneN-Qdv3ywQP5poecM)

HED [model](https://www.dropbox.com/sh/iawpm9nuqhcw6lh/AACMjlAVto6kuyy0m3gei3_9a?dl=0&lipi=urn%3Ali%3Apage%3Ad_flagship3_messaging%3BeXVpUjFUQ7OJbv5mIHkhIA%3D%3D) at 5K iterations.

**Comment by loveltyoic** [comment]
Yes, I can download them and run training!
Thanks for your job!

**Comment by kakoedlinnoe** [comment]
Thank you!
